export const norway = {
    info: `Vi hjelper bedrifter med å markedsføring på nett. Om det er reklame, responsiv nettside eller sosiale-medier kan vi hjelpe deg.`,
    ad: `Digital markedsføring gir deg en unik mulighet til å lage målrettet innhold på nett, akkurat der kundene dine er. For oss er hvert prosjekt unikt. Vi skreddersyr pakker for din bedrift, og gjør dine produkter og tjenester mer synlig.`,
    website: `Når man skal lage en nettside er det tre fagområder man må kunne: design, programmering på serversiden og programmering på klientsiden. I disse hovedområdene kreves det ekspertise for å få til en nettside med sterk visuell merkevare. Dette er SGS har lang erfaring med.`,
    social: `Det er over 4,7 milliarder sosiale mediebrukere rundt om i verden, altså 59% av verdens befolkning. Dette gjør det viktig for bedrifter å være representert med egne brukere for å denne store gruppen. Vi tilbyr å drive din bedrifts bruker for å gro den og maksimere dens effektivitet.`,
    aboutus: `Vi er strategere, analytikere og markedsførere med god erfaring. Dette gir oss muligheten til å forstå dine mål og utfordringer. Vi er spesialistene du trenger for å lyktes med digital markedsføring.\n\nVi er forretningsorienterte folk som tar utgangspunkt i dine forretningsmål. Du er eksperten på din bransje, mens vi er eksperter på det digitale. Sammen tar vi smarte valg som skaper verdi for deg og din bedrift.\n\nDu får en uredd partner som tar initiativ, utfordrer og får ting til å skje. Vi hjelper deg med å sette tydelige mål med markedsføringen, og vi måler effekten og resultatene av alt vi gjør.\n\nFor oss er samarbeid alt. Grunnen til dette er fordi samarbeid er lønnsomt og lærerikt. Når du jobber med SGS vil du oppleve at vi forstår dine visjoner og vil gjøre alt vi kan for å realisere dem. Det som gjør oss spesiell er vårt engasjement og vår kreativitet, med alt fra våre talentfulle kodere og webdesignere til kreative problemløsere garanterer vi at du vil bli fornøyd.`,
    whyus: `Google Ads er den største digitale markedsførings plattformen i verden og blant de mest lønnsomme. Vi hjelper deg med å benytte de unike og gode mulighetene Google Ads gir, slik at du oppnår de beste resultatene.\n\nInstagram er det ledende sosiale mediet for visuelt innhold. Plattformen er i stadig vekst, og med sine over én milliard månedlig aktive brukere, som gjøre plattformen til en av de beste i verden . Med gode muligheter for målretting og bygging av målgrupper, er Instagram en super plass å annonsere.\n\nMed sine mange muligheter for målretting og bygging av målgrupper, er Facebook en viktig kanal for annonsering og merkevarebygging. Vi har lang erfaring med strategi, innholdsproduksjon og segmentering på Facebook.\n\nGoogle, som er verdens største søkemotor, har en rekke krav og standarder som en nettside må oppfylle for å rangere godt i søkeresultatene. Et fokus på SEO er derfor viktig for at eksisterende og potensielle nye kunder skal finne deg på nett. `,
    giveusinfo: `For at vi kan få makedsførings prosessen til å bli mest mulig effektiv trenger vi å vite noen essensiell faktorer som målgrupper, overordnet budskap, budsjett og evt tidligere kampanjer.`,
    dontknow: `SGS marketing passer for fremtidsrettet selskaper som har  markedsføringsressurser, og som trenger hjelp av eksperter til å vurdere hvilke markedsmessige muligheter som finnes og hvordan disse best kan utnyttes.`,
}   